### ISSUE TITLE
cannot select version while creating server

### ISSUE THREAD

**Issue by MartijnStraatman** [grimsi/accservermanager-frontend#4]
I cannot select the version while creating the server.

**Comment by grimsi** [comment]
Did you follow the installation tutorial, especially the "Preparation" step?
https://github.com/grimsi/accservermanager/wiki/Set-up-the-server-executable-folder

**Comment by MartijnStraatman** [comment]
No, thanks.

Nicely done!
Maybe I’ll contribute.

**Comment by MartijnStraatman** [comment]
Will this work on a ubuntu-host?

**Comment by grimsi** [comment]
Yes this software is tested on Ubuntu 18 LTS

**Comment by MartijnStraatman** [comment]
Works!

Logs would be nice!
Can we steam those docker logs into the ui?

**Comment by grimsi** [comment]
Streaming logs to the UI is planned and currently in development, however it has to wait because the highest priority atm is getting my server manager ready for ACC 1.0

Please also take a look at the main repository: https://github.com/grimsi/accservermanager

**Comment by MartijnStraatman** [comment]
I am running this now on aws.

http://acc.streetman.io:8000 <http://acc.streetman.io:8000/>

It’s running 1.0.2

It would be nice if  a proper certificate is served. For example lets encrypt.
Maybe you can add some jks stuff. Or am I missing that?
Martijn

**Comment by grimsi** [comment]
I can't include a certificate in my software but you can add a lets encrypt certificate yourself.
See [https://accserver.grimsi.de](https://accserver.grimsi.de/login?returnUrl=%2F) as example

**Comment by MartijnStraatman** [comment]
I understand. Normally a certificate has to be read by the jks.
I could run a reverse-proxy in front with ssl termination.

**Comment by grimsi** [comment]
Im running a nginx reverse proxy and I think it's the easier and more flexible solution compared to have a built-in cert and a java keystore

Again, please open a new issue on the main repo if you have any other questions or need support.
